/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthVerify2faRouteImport } from './routes/auth/verify-2fa'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthMagicLinkSentRouteImport } from './routes/auth/magic-link-sent'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as marketingTermsRouteImport } from './routes/(marketing)/terms'
import { Route as marketingSupportRouteImport } from './routes/(marketing)/support'
import { Route as marketingPrivacyRouteImport } from './routes/(marketing)/privacy'
import { Route as marketingPricingRouteImport } from './routes/(marketing)/pricing'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as AuthForgetPasswordConfirmRouteImport } from './routes/auth/forget-password.confirm'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerify2faRoute = AuthVerify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMagicLinkSentRoute = AuthMagicLinkSentRouteImport.update({
  id: '/magic-link-sent',
  path: '/magic-link-sent',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const marketingTermsRoute = marketingTermsRouteImport.update({
  id: '/(marketing)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingSupportRoute = marketingSupportRouteImport.update({
  id: '/(marketing)/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingPrivacyRoute = marketingPrivacyRouteImport.update({
  id: '/(marketing)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingPricingRoute = marketingPricingRouteImport.update({
  id: '/(marketing)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthForgetPasswordConfirmRoute =
  AuthForgetPasswordConfirmRouteImport.update({
    id: '/forget-password/confirm',
    path: '/forget-password/confirm',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/pricing': typeof marketingPricingRoute
  '/privacy': typeof marketingPrivacyRoute
  '/support': typeof marketingSupportRoute
  '/terms': typeof marketingTermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link-sent': typeof AuthMagicLinkSentRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-2fa': typeof AuthVerify2faRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/forget-password/confirm': typeof AuthForgetPasswordConfirmRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/pricing': typeof marketingPricingRoute
  '/privacy': typeof marketingPrivacyRoute
  '/support': typeof marketingSupportRoute
  '/terms': typeof marketingTermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link-sent': typeof AuthMagicLinkSentRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-2fa': typeof AuthVerify2faRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/forget-password/confirm': typeof AuthForgetPasswordConfirmRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/(marketing)/pricing': typeof marketingPricingRoute
  '/(marketing)/privacy': typeof marketingPrivacyRoute
  '/(marketing)/support': typeof marketingSupportRoute
  '/(marketing)/terms': typeof marketingTermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link-sent': typeof AuthMagicLinkSentRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-2fa': typeof AuthVerify2faRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/forget-password/confirm': typeof AuthForgetPasswordConfirmRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/magic-link-sent'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-2fa'
    | '/auth/verify-email'
    | '/auth/forget-password/confirm'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/magic-link-sent'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-2fa'
    | '/auth/verify-email'
    | '/auth/forget-password/confirm'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/_protected'
    | '/(marketing)/pricing'
    | '/(marketing)/privacy'
    | '/(marketing)/support'
    | '/(marketing)/terms'
    | '/auth/forgot-password'
    | '/auth/magic-link-sent'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-2fa'
    | '/auth/verify-email'
    | '/auth/forget-password/confirm'
    | '/_protected/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  marketingPricingRoute: typeof marketingPricingRoute
  marketingPrivacyRoute: typeof marketingPrivacyRoute
  marketingSupportRoute: typeof marketingSupportRoute
  marketingTermsRoute: typeof marketingTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/verify-2fa': {
      id: '/auth/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/auth/verify-2fa'
      preLoaderRoute: typeof AuthVerify2faRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/magic-link-sent': {
      id: '/auth/magic-link-sent'
      path: '/magic-link-sent'
      fullPath: '/auth/magic-link-sent'
      preLoaderRoute: typeof AuthMagicLinkSentRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(marketing)/terms': {
      id: '/(marketing)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof marketingTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/support': {
      id: '/(marketing)/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof marketingSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/privacy': {
      id: '/(marketing)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof marketingPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/pricing': {
      id: '/(marketing)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof marketingPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/forget-password/confirm': {
      id: '/auth/forget-password/confirm'
      path: '/forget-password/confirm'
      fullPath: '/auth/forget-password/confirm'
      preLoaderRoute: typeof AuthForgetPasswordConfirmRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMagicLinkSentRoute: typeof AuthMagicLinkSentRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerify2faRoute: typeof AuthVerify2faRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthForgetPasswordConfirmRoute: typeof AuthForgetPasswordConfirmRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMagicLinkSentRoute: AuthMagicLinkSentRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerify2faRoute: AuthVerify2faRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthForgetPasswordConfirmRoute: AuthForgetPasswordConfirmRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  marketingPricingRoute: marketingPricingRoute,
  marketingPrivacyRoute: marketingPrivacyRoute,
  marketingSupportRoute: marketingSupportRoute,
  marketingTermsRoute: marketingTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
